apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: websocketservice
    env: testing
  name: websocketservice
  namespace: eventms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocketservice
  template:
    metadata:
      labels:
        app: websocketservice
        env: testing
      namespace: eventms
    spec:
      containers:
      - image: eventms/websocket.api:linux
        name: websocketservice
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ConnectionString
            value: "Server=eventms-database;Database=Services.websocketDb;User Id=sa;Password=Pass@word"
          - name: EventBusConnection
            value: "rabbitmq"
