apiVersion: v1
kind: Service
metadata:
  labels:
    app: websocketservice
    env: testing
  name: websocketservice
  namespace: eventms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: websocketservice
  type: ClusterIP
