apiVersion: v1
kind: Service
metadata:
  labels:
    app: paymentwebhookservice
    env: testing
  name: paymentwebhookservice
  namespace: eventms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: paymentwebhookservice
  type: ClusterIP
