apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
    env: testing
  name: rabbitmq
  namespace: eventms
spec:
  ports:
  - name: admin
    port: 15672
    protocol: TCP
    targetPort: admin
  - name: messages
    port: 5672
    protocol: TCP
    targetPort: messages
  selector:
    app: rabbitmq
  type: ClusterIP