apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
    env: testing
  name: rabbitmq
  namespace: eventms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        env: testing
      namespace: eventms
    spec:
      containers:
      - image: rabbitmq:3-management-alpine
        name: rabbitmq
        volumeMounts:
        - name: rabbitmq-pv
          mountPath: /var/lib/rabbitmq
        resources: {}
        ports: 
          - name: admin  # Admin-panel: http://localhost:15672/#/ (guest:guest)
            containerPort: 15672
          - name: messages
            containerPort: 5672
      volumes:
        - name: rabbitmq-pv
          persistentVolumeClaim:
            claimName: rabbitmq-pvc