apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: permission-api
    env: testing
  name: permission-api
  namespace: eventms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: permission-api
  template:
    metadata:
      labels:
        app: permission-api
        env: testing
      namespace: eventms
    spec:
      containers:
      - image: eventms/permission.api:linux
        name: permission-api
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ConnectionString
            value: "Server=eventms-database;Database=Services.permissionDb;User Id=sa;Password=Pass@word"
          - name: EventBusConnection
            value: "message-queue"
