apiVersion: v1
kind: Service
metadata:
  labels:
    app: websocket-api
    env: testing
  name: websocket-api
  namespace: eventms
  annotations: 
    cloud.google.com/backend-config: '{"ports": {"80":"my-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: websocket-api
  type: NodePort
