apiVersion: v1
kind: Service
metadata:
  labels:
    app: club-api
    env: testing
  name: club-api
  namespace: eventms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: club-api
  type: NodePort
