apiVersion: v1
kind: Service
metadata:
  labels:
    app: template1service
    env: testing
  name: template1service
  namespace: eventms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: template1service
  type: ClusterIP