apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: eventms
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: #itonk-ap2-gr2.dk -  Maybe localhost or eventms.dk -> Would require change of host file. 
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
              name: graphqlservice
              port:
                number: 80   
      - path: /rabbitmq(/|$)(.*) #admin rabbit
        pathType: Prefix
        backend:
            service: 
               name: message-queue
               port:
                 number: 15672     
     # - path: /(/|$)(.*)
     #   pathType: Prefix
     #   backend:
      #    service:
      #        name: frontendservice
     #         port:
      #          number: 80   