apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: identityservice
    env: testing
  name: identityservice
  namespace: eventms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityservice
  template:
    metadata:
      labels:
        app: identityservice
        env: testing
      namespace: eventms
    spec:
      containers:
      - image: eventms/identity.api:linux
        name: identityservice
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ConnectionString
            value: "Server=sqldata;Database=Services.identityDb;User Id=sa;Password=Pass@word"
          - name: EventBusConnection
            value: "rabbitmq"
