apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subscriptionservice
    env: testing
  name: subscriptionservice
  namespace: eventms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptionservice
  template:
    metadata:
      labels:
        app: subscriptionservice
        env: testing
      namespace: eventms
    spec:
      containers:
      - image: eventms/subscription.api:linux
        name: subscriptionservice
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ConnectionString
            value: "Server=sqldata;Database=Services.subscriptionDb;User Id=sa;Password=Pass@word"
          - name: EventBusConnection
            value: "rabbitmq"
