apiVersion: v1
kind: Service
metadata:
  labels:
    app: subscriptionservice
    env: testing
  name: subscriptionservice
  namespace: eventms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: subscriptionservice
  type: ClusterIP
