apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eventverificationservice
    env: testing
  name: eventverificationservice
  namespace: eventms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventverificationservice
  template:
    metadata:
      labels:
        app: eventverificationservice
        env: testing
      namespace: eventms
    spec:
      containers:
      - image: eventms/eventverification.api:linux
        name: eventverificationservice
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ConnectionString
            value: "Server=eventms-database;Database=Services.eventverificationDb;User Id=sa;Password=Pass@word"
          - name: EventBusConnection
            value: "message-queue"
