apiVersion: v1
kind: Service
metadata:
  labels:
    app: eventVerificationservice
    env: testing
  name: eventVerificationservice
  namespace: eventms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: eventVerificationservice
  type: ClusterIP
