apiVersion: v1
kind: Service
metadata:
  labels:
    app: eventms-database
    env: production
  name: eventms-database
  namespace: eventms
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: eventms-database
  type: LoadBalancer