kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-base-volume
  namespace: eventms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-mdf-volume
  namespace: eventms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-ldf-volume
  namespace: eventms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi