// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using EMS.PaymentWebhook_Services.API.Context;

namespace EMS.PaymentWebhook_Services.API.Migrations
{
    [DbContext(typeof(PaymentWebhookContext))]
    partial class PaymentWebhookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentWebhook.API.Context.Model.PaymentWebhook", b =>
                {
                    b.Property<Guid>("PaymentWebhookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentWebhookId");

                    b.ToTable("PaymentWebhook");
                });
#pragma warning restore 612, 618
        }
    }
}
