apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clubservice
    env: testing
  name: clubservice
  namespace: eventms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clubservice
  template:
    metadata:
      labels:
        app: clubservice
        env: testing
      namespace: eventms
    spec:
      containers:
      - image: eventms/club.api:linux
        name: clubservice
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ConnectionString
            value: "Server=eventms-database;Database=Services.clubDb;User Id=sa;Password=Pass@word"
          - name: EventBusConnection
            value: "rabbitmq"
