version: '3.4'

services:

  #seq:
  #  image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity-api:
    image: eventms/identity.api:linux
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  club-api:
    image: eventms/club.api:linux
    build:
      context: .
      dockerfile: Services/Club/Club.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  permission-api:
    image: eventms/permission.api:linux
    build:
      context: .
      dockerfile: Services/Permission/Permission.API/Dockerfile
    depends_on:
      - sqldata
      - identity-api
      - rabbitmq

  subscription-api:
    image: eventms/subscription.api:linux
    build:
      context: .
      dockerfile: Services/Subscription/Subscription.API/Dockerfile
    depends_on:
      - sqldata
      - identity-api
      - rabbitmq

  clubmember-api:
    image: eventms/clubmember.api:linux
    build:
      context: .
      dockerfile: Services/ClubMember/ClubMember.API/Dockerfile
    depends_on:
      - sqldata
      - identity-api
      - rabbitmq

  room-api:
    image: eventms/room.api:linux
    build:
      context: .
      dockerfile: Services/Room/Room.API/Dockerfile
    depends_on:
      - sqldata
      - identity-api
      - rabbitmq

  event-api:
    image: eventms/event.api:linux
    build:
      context: .
      dockerfile: Services/Event/Event.API/Dockerfile
    depends_on:
      - sqldata
      - identity-api
      - rabbitmq

  eventparticipant-api:
    image: eventms/eventparticipant.api:linux
    build:
      context: .
      dockerfile: Services/EventParticipant/EventParticipant.API/Dockerfile
    depends_on:
      - sqldata
      - identity-api
      - rabbitmq

  paymentwebhook-api:
    image: eventms/paymentwebhook.api:linux
    build:
      context: .
      dockerfile: Services/PaymentWebhook/PaymentWebhook.API/Dockerfile
    depends_on:
      - sqldata
      - identity-api
      - rabbitmq

  websocket-api:
    image: eventms/websocket.api:linux
    build:
      context: .
      dockerfile: Services/Websocket/Websocket.API/Dockerfile
    depends_on:
      - sqldata
      - identity-api
      - rabbitmq

  payment-api:
    image: eventms/payment.api:linux
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - sqldata
      - identity-api
      - rabbitmq

  eventverification-api:
    image: eventms/eventverification.api:linux
    build:
      context: .
      dockerfile: Services/EventVerification/EventVerification.API/Dockerfile
    depends_on:
      - sqldata
      - identity-api
      - rabbitmq

  frontend:
    image: eventms/frontend:dev
    depends_on:
      - sqldata
      - graphql-api
      - rabbitmq

  graphql-api:
    image: eventms/graphql.api:linux
    build:
      context: .
      dockerfile: ApiGateways/GraphQL/GraphQL.API/Dockerfile
    depends_on:
      - identity-api
      - club-api
      - permission-api
      - subscription-api
      - clubmember-api
      - room-api
      - eventparticipant-api
      - event-api
      - payment-api
      - eventverification-api