version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The EMS_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     EMS_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - eshop-sqldata:/var/opt/mssql

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - PORT=80
      - PATH_BASE=/identity-api
      - ConnectionString=${ESHOP_AZURE_IDENTITY_DB:-Server=sqldata;Database=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5101:80"

  graphql-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${ESHOP_AZURE_CATALOG_DB:-Server=sqldata;Database=Microsoft.eShopOnContainers.Services.GraphQLDb;User Id=sa;Password=Pass@word}
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${EMS_DNS_NAME_OR_IP}:5101
      - PicBaseUrl=${ESHOP_STORAGE_CATALOG_URL}
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - PORT=80
      - PATH_BASE=/graphql-api
      - services=template1-api,identity-api
    ports:
      - "5102:80"


  template1-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${ESHOP_AZURE_CATALOG_DB:-Server=sqldata;Database=Microsoft.eShopOnContainers.Services.Template1Db;User Id=sa;Password=Pass@word}
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${EMS_DNS_NAME_OR_IP}:5101
      - PicBaseUrl=${ESHOP_STORAGE_CATALOG_URL}
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - PORT=80
      - PATH_BASE=/template1-api
    ports:
      - "5103:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
  #    - HealthChecksUI__HealthChecks__0__Name=Identity API HTTP Check
  #    - HealthChecksUI__HealthChecks__0__Uri=http://identity-api/hc
  #    - HealthChecksUI__HealthChecks__1__Name=Graph QL gateway HTTP Check
  #    - HealthChecksUI__HealthChecks__1__Uri=http://graphql-api/hc
  #    - HealthChecksUI__HealthChecks__2__Name=Template1 Http Check
  #    - HealthChecksUI__HealthChecks__2__Uri=http://template1-api/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5104:80"

volumes:
  eshop-sqldata:
    external: false

