version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The EMS_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     EMS_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - ems-sqldata:/var/opt/mssql

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=rabbitmq
      - PORT=80
      - PATH_BASE=/identity-api
      - ConnectionString=Server=sqldata;Database=Services.IdentityDb;User Id=sa;Password=Pass@word
    ports:
      - "5101:80"

  graphql-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=Services.GraphQLDb;User Id=sa;Password=Pass@word
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${EMS_DNS_NAME_OR_IP}:5101
      - EventBusConnection=rabbitmq
      - PORT=80
      - PATH_BASE=/graphql-api
      - services=template1-api,identity-api,club-api,subscription-api,clubmember-api
    ports:
      - "5102:80"


  template1-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=Services.Template1Db;User Id=sa;Password=Pass@word
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${EMS_DNS_NAME_OR_IP}:5101
      - EventBusConnection=rabbitmq
      - PORT=80
      - PATH_BASE=/template1-api
    ports:
      - "5103:80"

  club-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=Services.ClubDb;User Id=sa;Password=Pass@word
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${EMS_DNS_NAME_OR_IP}:5101
      - EventBusConnection=rabbitmq
      - PORT=80
      - PATH_BASE=/club-api
    ports:
      - "5106:80"

  permission-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=Services.PermissionDb;User Id=sa;Password=Pass@word
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${EMS_DNS_NAME_OR_IP}:5101
      - EventBusConnection=rabbitmq
      - PORT=80
      - PATH_BASE=/permission-api
    ports:
      - "5105:80"

  subscription-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=Services.SubscriptionDb;User Id=sa;Password=Pass@word
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${EMS_DNS_NAME_OR_IP}:5101
      - EventBusConnection=rabbitmq
      - PORT=80
      - PATH_BASE=/subscription-api
    ports:
      - "5107:80"

  clubmember-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sqldata;Database=Services.ClubMemberDb;User Id=sa;Password=Pass@word
      - identityUrl=http://identity-api
      - IdentityUrlExternal=http://${EMS_DNS_NAME_OR_IP}:5101
      - EventBusConnection=rabbitmq
      - PORT=80
      - PATH_BASE=/clubmember-api
    ports:
      - "5108:80"

volumes:
  ems-sqldata:
    external: false

