docker push eventms/event.api:linux
docker push eventms/identity.api:linux
docker push eventms/club.api:linux
docker push eventms/graphql.api:linux
docker push eventms/payment.api:linux
docker push eventms/room.api:linux
docker push eventms/websocket.api:linux
docker push eventms/eventparticipant.api:linux
docker push eventms/clubmember.api:linux
docker push eventms/paymentwebhook.api:linux
docker push eventms/subscription.api:linux
docker push eventms/eventverification.api:linux
docker push eventms/permission.api:linux
