apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roomservice
    env: testing
  name: roomservice
  namespace: eventms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roomservice
  template:
    metadata:
      labels:
        app: roomservice
        env: testing
      namespace: eventms
    spec:
      containers:
      - image: eventms/room.api:linux
        name: roomservice
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ConnectionString
            value: "Server=eventms-database;Database=Services.roomDb;User Id=sa;Password=Pass@word"
          - name: EventBusConnection
            value: "message-queue"
