apiVersion: v1
kind: Service
metadata:
  labels:
    app: roomservice
    env: testing
  name: roomservice
  namespace: eventms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: roomservice
  type: ClusterIP
