apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eventservice
    env: testing
  name: eventservice
  namespace: eventms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventservice
  template:
    metadata:
      labels:
        app: eventservice
        env: testing
      namespace: eventms
    spec:
      containers:
      - image: eventms/event.api:linux
        name: eventservice
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ConnectionString
            value: "Server=eventms-database;Database=Services.eventDb;User Id=sa;Password=Pass@word"
          - name: EventBusConnection
            value: "rabbitmq"
