apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paymentservice
    env: testing
  name: paymentservice
  namespace: eventms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
        env: testing
      namespace: eventms
    spec:
      containers:
      - image: eventms/payment.api:linux
        name: paymentservice
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ConnectionString
            value: "Server=sqldata;Database=Services.paymentDb;User Id=sa;Password=Pass@word"
          - name: EventBusConnection
            value: "rabbitmq"
