apiVersion: v1
kind: Service
metadata:
  labels:
    app: paymentservice
    env: testing
  name: paymentservice
  namespace: eventms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: paymentservice
  type: ClusterIP
